parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Dto/'
            - '../src/Entity/'
            - '../src/Extractor/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Symfony\Component\VarDumper\Cloner\VarCloner:
        public: true

    # replace the DebugExtension by the DumpExtension to have beautiful HTML dumps in twig
    twig.extension.debug:
        class: Symfony\Bridge\Twig\Extension\DumpExtension
        arguments:
            - '@Symfony\Component\VarDumper\Cloner\VarCloner'
        tags:
            - { name: twig.extension }
