name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: yarn install --frozen-lockfile

      - run: |
          yarn build
          cp index.html dist/index.html
          sed -i "s/dist\/bundle.js/bundle.js?t=$(date +%s)/g" dist/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
