name: Lint

on: push

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn stylelint
