name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile

      - run: yarn lint
      - run: yarn stylelint

  symfony:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/symfonyapp
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: composer install
      - run: vendor/bin/php-cs-fixer fix --dry-run --verbose --diff
      - run: bin/console --env=test lint:twig templates
      - run: bin/console --env=test lint:yaml config
